### PR TITLE
Implemented RegisterServlet at /register

### PR DESCRIPTION
**Pull request by spdunn**
Implemented RegisterServlet, updated .gitignore, and apparently created ResourceNotFoundException

### CODE REVIEW

**Comment by batainem96** [comment]
The RegisterServlet still has the example doGet method

**Comment by spdunn** [comment]
Forgot about that...

**Comment by batainem96** [comment]
~.^

**Comment by spdunn** [comment]
Guess we need to work on converting Students into DTOs before we can fully implement Register, so Imma get crackin on that first

**Pull request merged**
